"""fixing db'


Revision ID: 2f53340a6618
Revises: 74fb8213fa09
Create Date: 2021-08-22 19:16:45.380763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f53340a6618'
down_revision = '74fb8213fa09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('detail_user_ibfk_1', 'detail_user', type_='foreignkey')
    op.create_foreign_key(None, 'detail_user', 'users', ['id_user'], ['id_user'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('evaluation', 'study_time',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('evaluation', 'freetime',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint('evaluation_ibfk_1', 'evaluation', type_='foreignkey')
    op.drop_constraint('evaluation_ibfk_3', 'evaluation', type_='foreignkey')
    op.drop_constraint('evaluation_ibfk_2', 'evaluation', type_='foreignkey')
    op.create_foreign_key(None, 'evaluation', 'course_subject', ['id_course'], ['id_course'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'evaluation', 'users', ['id_user'], ['id_user'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'evaluation', 'target', ['id_target'], ['id_target'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evaluation', type_='foreignkey')
    op.drop_constraint(None, 'evaluation', type_='foreignkey')
    op.drop_constraint(None, 'evaluation', type_='foreignkey')
    op.create_foreign_key('evaluation_ibfk_2', 'evaluation', 'target', ['id_target'], ['id_target'])
    op.create_foreign_key('evaluation_ibfk_3', 'evaluation', 'users', ['id_user'], ['id_user'])
    op.create_foreign_key('evaluation_ibfk_1', 'evaluation', 'course_subject', ['id_course'], ['id_course'])
    op.alter_column('evaluation', 'freetime',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('evaluation', 'study_time',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint(None, 'detail_user', type_='foreignkey')
    op.create_foreign_key('detail_user_ibfk_1', 'detail_user', 'users', ['id_user'], ['id_user'])
    # ### end Alembic commands ###
