"""create database

Revision ID: 74fb8213fa09
Revises: 
Create Date: 2021-08-22 12:02:38.400981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74fb8213fa09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_subject',
    sa.Column('id_course', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('course_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_course')
    )
    op.create_table('users',
    sa.Column('id_user', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('Admin', 'User'), nullable=False),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('detail_user',
    sa.Column('id_detail_user', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('age', sa.BigInteger(), nullable=True),
    sa.Column('genre', sa.Enum('Male', 'Female'), nullable=True),
    sa.Column('internet', sa.Enum('Yes', 'No'), nullable=True),
    sa.Column('fjob', sa.String(length=50), nullable=True),
    sa.Column('mjob', sa.String(length=50), nullable=True),
    sa.Column('pstatus', sa.Enum('Yes', 'No'), nullable=True),
    sa.Column('id_user', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_detail_user')
    )
    op.create_table('target',
    sa.Column('id_target', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.BigInteger(), nullable=True),
    sa.Column('id_course', sa.BigInteger(), nullable=True),
    sa.Column('g1', sa.Integer(), nullable=False),
    sa.Column('grade_target', sa.Integer(), nullable=False),
    sa.Column('target_time', sa.Integer(), nullable=False),
    sa.Column('achived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_course'], ['course_subject.id_course'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_target')
    )
    op.create_table('evaluation',
    sa.Column('id_evaluation', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.BigInteger(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('study_time', sa.Integer(), nullable=False),
    sa.Column('freetime', sa.Integer(), nullable=False),
    sa.Column('id_course', sa.BigInteger(), nullable=True),
    sa.Column('id_target', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_course'], ['course_subject.id_course'], ),
    sa.ForeignKeyConstraint(['id_target'], ['target.id_target'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_evaluation')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluation')
    op.drop_table('target')
    op.drop_table('detail_user')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('course_subject')
    # ### end Alembic commands ###
