"""fixing db

Revision ID: c4b3ff75c443
Revises: 2f53340a6618
Create Date: 2021-08-22 19:18:57.284675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4b3ff75c443'
down_revision = '2f53340a6618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evaluation', 'study_time',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('evaluation', 'freetime',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evaluation', 'freetime',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('evaluation', 'study_time',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
